services:

    postgres:
        image: "postgres:15"
        container_name: postgres
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
        ports:
            - '5432:5432'

    mailpit:
        image: "axllent/mailpit:v1.22.3"
        container_name: mailpit
        ports:
            - '1025:1025'
            - '8025:8025'
