"""add new column

Revision ID: 2fbff4725664
Revises: a624bff2c7e1
Create Date: 2025-03-19 19:25:54.184124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbff4725664'
down_revision: Union[str, None] = 'a624bff2c7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('family_name', sa.String(), nullable=False, server_default="Unk"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'family_name')
    # ### end Alembic commands ###
