// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Subscription API
//
//	Subscription API
//	Schemes:
//	  https
//	Host: localhost
//	BasePath: /subscribe/v1
//	Version: 0.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
