services:
# TODO: use same env var in services and in application.conf
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user

  redis:
    image: redis:7.4
    restart: always
    ports:
      - '6379:6379'

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: dummy
      MINIO_ROOT_PASSWORD: dummy1234
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " sleep 10; mc alias set myminio http://minio:9000 dummy dummy1234 --api S3v4; mc mb myminio/my-pet-service; mc cp rabbit.jpg myminio/my-pet-service; exit 0; "
    volumes:
      - ./../images/rabbit.jpg:/rabbit.jpg

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SASL_ENABLED: "false"
    expose:
      - 2181
    healthcheck:
      test: "nc -z localhost 2181 || exit -1"
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10

  kafka:
    image: confluentinc/cp-kafka:latest
    expose:
      - 9093
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "BROKER://kafka:9093,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "BROKER"
      KAFKA_BROKER_ID: "1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      ZOOKEEPER_SASL_ENABLED: "false"
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: "nc -z localhost 9093 || exit -1"
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10

  kafka-setup:
    image: confluentinc/cp-kafka:latest
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
              cub kafka-ready -b kafka:9093 1 30 && \
              echo Creating topics... && \
              kafka-topics --create --bootstrap-server kafka:9093 --partitions 1 --replication-factor 1 --topic animals-input && \
              kafka-topics --create --bootstrap-server kafka:9093 --partitions 1 --replication-factor 1 --topic animals-update'"

  my-pet-service:
    depends_on:
      - minio
      - createbuckets
      - redis
      - postgres
      - kafka-setup
    image: tbank-ab:0.1.0-SNAPSHOT
    ports:
      - "8080:8080"
      - "8083:8083"
    environment:
      AUTH_LOGIN: my_login
      AUTH_PASS: my_password
