// Code generated by go-swagger; DO NOT EDIT.

package secure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AuthCheckHandlerFunc turns a function with the right signature into a auth check handler
type AuthCheckHandlerFunc func(AuthCheckParams, interface{}) AuthCheckResponder

// Handle executing the request and returning a response
func (fn AuthCheckHandlerFunc) Handle(params AuthCheckParams, principal interface{}) AuthCheckResponder {
	return fn(params, principal)
}

// AuthCheckHandler interface for that can handle valid auth check params
type AuthCheckHandler interface {
	Handle(AuthCheckParams, interface{}) AuthCheckResponder
}

// NewAuthCheck creates a new http.Handler for the auth check operation
func NewAuthCheck(ctx *middleware.Context, handler AuthCheckHandler) *AuthCheck {
	return &AuthCheck{Context: ctx, Handler: handler}
}

/*
	AuthCheck swagger:route GET /auth-check secure authCheck

check service work correctly
*/
type AuthCheck struct {
	Context *middleware.Context
	Handler AuthCheckHandler
}

func (o *AuthCheck) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAuthCheckParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
