// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	TasksGetOperation          OperationName = "TasksGet"
	TasksPostOperation         OperationName = "TasksPost"
	TasksTaskIdDeleteOperation OperationName = "TasksTaskIdDelete"
	TasksTaskIdGetOperation    OperationName = "TasksTaskIdGet"
	TasksTaskIdPutOperation    OperationName = "TasksTaskIdPut"
)
