// Code generated by ogen, DO NOT EDIT.
package api

type TasksPostRes interface {
	tasksPostRes()
}

type TasksTaskIdDeleteRes interface {
	tasksTaskIdDeleteRes()
}

type TasksTaskIdGetRes interface {
	tasksTaskIdGetRes()
}

type TasksTaskIdPutRes interface {
	tasksTaskIdPutRes()
}
