// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// TasksGet implements GET /tasks operation.
//
// Получить список всех задач.
//
// GET /tasks
func (UnimplementedHandler) TasksGet(ctx context.Context) (r []Task, _ error) {
	return r, ht.ErrNotImplemented
}

// TasksPost implements POST /tasks operation.
//
// Создать новую задачу.
//
// POST /tasks
func (UnimplementedHandler) TasksPost(ctx context.Context, req *TaskInput) (r TasksPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TasksTaskIdDelete implements DELETE /tasks/{taskId} operation.
//
// Удалить задачу.
//
// DELETE /tasks/{taskId}
func (UnimplementedHandler) TasksTaskIdDelete(ctx context.Context, params TasksTaskIdDeleteParams) (r TasksTaskIdDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TasksTaskIdGet implements GET /tasks/{taskId} operation.
//
// Получить задачу по ID.
//
// GET /tasks/{taskId}
func (UnimplementedHandler) TasksTaskIdGet(ctx context.Context, params TasksTaskIdGetParams) (r TasksTaskIdGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TasksTaskIdPut implements PUT /tasks/{taskId} operation.
//
// Обновить существующую задачу.
//
// PUT /tasks/{taskId}
func (UnimplementedHandler) TasksTaskIdPut(ctx context.Context, req *TaskInput, params TasksTaskIdPutParams) (r TasksTaskIdPutRes, _ error) {
	return r, ht.ErrNotImplemented
}
