// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// BaseResponse universal response is used for NoContent and AnyError answers, contains field Status as any data answers
//
// swagger:model baseResponse
type BaseResponse interface{}
