### GET inventory sync job status
GET localhost:8081/actuator/inventorySync

### POST disabling inventory sync job
POST localhost:8081/actuator/inventorySync/false
Content-Type: application/json

### GET room type inventory list
GET localhost:8081/api/inventory

### POST a new reservation. !Use current date in startDate, adjust endDate!
POST localhost:8081/api/reservations
Content-Type: application/json

{
    "hotel_id": 2,
    "room_type_id": 4,
    "start_date": "2025-05-03",
    "end_date": "2025-05-06",
    "guest_id": 123
}

### GET reservations for the specified user
GET localhost:8081/api/guests/123/reservations
