services:
  cache:
    image: valkey/valkey:7.2.5
    command: ["valkey-server", "/etc/valkey/valkey.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./valkey.conf:/etc/valkey/valkey.conf
      - ./users.acl:/etc/valkey/users.acl
    restart: unless-stopped
