"""add culture to character

Revision ID: 2d5546e00467
Revises: 1902ee47bce7
Create Date: 2023-03-15 17:27:27.510905

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "2d5546e00467"
down_revision = "1902ee47bce7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "character",
        sa.Column(
            "culture", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("character", "culture")
    # ### end Alembic commands ###
