name: Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  my-job:
    runs-on: edu-self-hosted
    timeout-minutes: 10
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-21.0.6_7_1.10.10_2.13.16
    steps:
      - run: echo "Ok"
