name: Docker Test
on: [push]

jobs:
  docker-test:
    runs-on: self-hosted
    services:
      docker-dind:
        image: docker:dind
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""
        options: --network host  # Используем хост-сеть для сервиса
    container:
      image: docker:cli
      options: --network host  # Подключаем основной контейнер к хост-сети
    steps:
      - name: Test connection
        run: |
          docker --version
          export DOCKER_HOST=tcp://localhost:2375
          docker info
          
      - name: Run Hello-World
        run: |
          export DOCKER_HOST=tcp://localhost:2375
          docker run --rm hello-world
