name: Test CI

on: [push]

jobs:
  my-job:
    runs-on: edu-self-hosted
    timeout-minutes: 10
    services:
      docker:
        image: docker:dind
        ports:
          - 2375:2375
    steps:
      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          docker --version
          echo "DOCKER_HOST=tcp://docker:2375" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker version
          docker info
