name: Test CI

on: [push]

jobs:
  my-job:
    runs-on: edu-self-hosted
    services:
      docker-dind:
        image: docker:dind
        ports:
          - 2375:2375
    steps:
      - name: Setup Docker
        run: |
          echo "DOCKER_HOST=tcp://localhost:2375" >> $GITHUB_ENV
          
      - name: Test
        run: docker version
