name: Test CI

on: [push]

jobs:
  my-job:
    runs-on: edu-self-hosted
    timeout-minutes: 10
    services:
      docker-dind:
        image: docker:dind
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""
    container:
      image: ubuntu:latest
    steps:
      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io
          docker --version
      # Настраиваем окружение для работы с DinD
      - name: Configure Docker
        env:
          DOCKER_HOST: tcp://docker-dind:2375
        run: |
          echo "DOCKER_HOST=$DOCKER_HOST" >> $GITHUB_ENV
          docker version
