name: Docker Test
on: [push]

jobs:
  docker-test:
    runs-on: edu-self-hosted
    services:
      docker-dind:
        image: docker:dind
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""  # Отключаем TLS (упрощаем подключение)
    container:
      image: docker:cli  # Официальный образ с Docker CLI
      options: --add-host docker-dind:host-gateway  # Позволяет резолвить docker-dind
    steps:
      - name: Run Hello-World
        run: |
          docker --version
          export DOCKER_HOST=tcp://docker-dind:2375  # Подключаемся к Docker демону
          docker run --rm hello-world
