name: Docker Test

on: [push]

jobs:
  docker-test:
    runs-on: edu-self-hosted
    timeout-minutes: 5
    container:
      image: ubuntu:latest
    steps:
      - name: Check Docker installation
        run: |
          docker --version
          docker info

      - name: Run Hello-World
        run: |
          docker run --rm hello-world
