name: Test CI

on: [push]

jobs:
  my-job:
    runs-on: edu-self-hosted
    timeout-minutes: 10
    services:
      docker:
        image: docker:dind-rootless
        options: --privileged
        ports:
          - 2375:2375
    container:
      image: ubuntu:latest
    steps:
      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io
          docker --version
          docker version
