name: Test CI

on: [push]

jobs:
  my-job:
    runs-on: edu-self-hosted
    timeout-minutes: 10
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-21.0.6_7_1.10.10_2.13.16
    steps:
      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io
          docker --version
          docker version
