name: Docker Test
on: [push]

jobs:
  docker-test:
    runs-on: edu-self-hosted
    container:
      image: docker:cli
      options: -v /var/run/docker.sock:/var/run/docker.sock  # Монтируем сокет хоста
    steps:
      - name: Run Hello-World
        run: |
          docker run --rm hello-world
