name: Docker Test

on: [push]

jobs:
  docker-test:
    runs-on: edu-self-hosted
    container: docker:cli  # Официальный образ с предустановленным Docker CLI
    steps:
      - name: Run Hello-World
        run: |
          docker --version
          docker run --rm hello-world
